public class GTUTest{
	public static void main(String[] args){
		System.out.println("**********************************************");
    	System.out.println("\t***GTUSet TEST<INTEGER>***");
    	GTUSet<Integer> objeSet = new GTUSet<Integer>();
    	System.out.println("*INSERT Test*");
    	System.out.println("5-1-2-4-7 (inserting)");
    	objeSet.insert(5);
    	objeSet.insert(1);
    	objeSet.insert(2);
    	objeSet.insert(4);
    	objeSet.insert(7);
    	objeSet.print();
    	System.out.println("*ERASE Test*");
    	System.out.println("2 is erasing");
    	objeSet.erase(2);
    	objeSet.print();
    	System.out.println("*EMPTY Test*");
    	System.out.println("Is it empty?");
    	System.out.printf("%b\n",objeSet.empty());
    	System.out.println("*CONTAIN Test*");
    	System.out.println("Are there 5 in the Set?");
    	System.out.printf("%b\n",objeSet.contains(5));
    	System.out.println("Are there 9 in the Set?");
    	System.out.printf("%b\n",objeSet.contains(9));
    	System.out.println("*CLEAR Test*");
    	objeSet.clear();
    	System.out.println("Print Set");
    	objeSet.print();
    	System.out.println("*EMPTY Test*");
    	System.out.println("Is it empty?");
    	System.out.printf("%b\n",objeSet.empty());

    	System.out.println("**********************************************");
    	System.out.println("\t***GTUSet TEST<STRING>***");
    	GTUSet<String> objeSet2 = new GTUSet<String>();
    	System.out.println("*INSERT Test*");
    	System.out.println("a-b-c-d-e (inserting)");
    	objeSet2.insert("a");
    	objeSet2.insert("b");
    	objeSet2.insert("c");
    	objeSet2.insert("d");
    	objeSet2.insert("e");
    	objeSet2.print();
    	System.out.println("*ERASE Test*");
    	System.out.println("c is erasing");
    	objeSet2.erase("c");
    	objeSet2.print();
    	System.out.println("*EMPTY Test*");
    	System.out.println("Is it empty?");
    	System.out.printf("%b\n",objeSet2.empty());
    	System.out.println("*CONTAIN Test*");
    	System.out.println("Are there b in the Set?");
    	System.out.printf("%b\n",objeSet2.contains("b"));
    	System.out.println("Are there h in the Set?");
    	System.out.printf("%b\n",objeSet2.contains("h"));
    	System.out.println("*CLEAR Test*");
    	objeSet2.clear();
    	System.out.println("Print Set");
    	objeSet2.print();
    	System.out.println("*EMPTY Test*");
    	System.out.println("Is it empty?");
    	System.out.printf("%b\n",objeSet2.empty());

    	System.out.println("**********************************************");
    	System.out.println("\t***GTUVector TEST<INTEGER>***");
    	GTUVector<Integer> objeSet3 = new GTUVector<Integer>();
    	System.out.println("*INSERT Test*");
    	System.out.println("5-6-7-8-9 (inserting)");
    	objeSet3.insert(5);
    	objeSet3.insert(6);
    	objeSet3.insert(7);
    	objeSet3.insert(8);
    	objeSet3.insert(9);
    	objeSet3.print();
    	System.out.println("*ERASE Test*");
    	System.out.println("7 is erasing");
    	objeSet3.erase(7);
    	objeSet3.print();
    	System.out.println("*EMPTY Test*");
    	System.out.println("Is it empty?");
    	System.out.printf("%b\n",objeSet3.empty());
    	System.out.println("*CONTAIN Test*");
    	System.out.println("Are there 9 in the Set?");
    	System.out.printf("%b\n",objeSet3.contains(9));
    	System.out.println("Are there 10 in the Set?");
    	System.out.printf("%b\n",objeSet3.contains(10));
    	System.out.println("*CLEAR Test*");
    	objeSet3.clear();
    	System.out.println("Print Set");
    	objeSet3.print();
    	System.out.println("*EMPTY Test*");
    	System.out.println("Is it empty?");
    	System.out.printf("%b\n",objeSet3.empty());

    	System.out.println("**********************************************");
    	System.out.println("\t***GTUVector TEST<STRING>***");
    	GTUVector<String> objeSet5 = new GTUVector<String>();
    	System.out.println("*INSERT Test*");
    	System.out.println("y-c-k-d-b (inserting)");
    	objeSet5.insert("y");
    	objeSet5.insert("c");
    	objeSet5.insert("k");
    	objeSet5.insert("d");
    	objeSet5.insert("b");
    	objeSet5.print();
    	System.out.println("*ERASE Test*");
    	System.out.println("c is erasing");
    	objeSet5.erase("c");
    	objeSet5.print();
    	System.out.println("*EMPTY Test*");
    	System.out.println("Is it empty?");
    	System.out.printf("%b\n",objeSet5.empty());
    	System.out.println("*CONTAIN Test*");
    	System.out.println("Are there b in the Set?");
    	System.out.printf("%b\n",objeSet5.contains("b"));
    	System.out.println("Are there h in the Set?");
    	System.out.printf("%b\n",objeSet5.contains("h"));
    	System.out.println("*CLEAR Test*");
    	objeSet5.clear();
    	System.out.println("Print Set");
    	objeSet5.print();
    	System.out.println("*EMPTY Test*");
    	System.out.println("Is it empty?");
    	System.out.printf("%b\n",objeSet5.empty());
	}
}